name: "speckle-server"

services:
  ####
  # Speckle Server dependencies
  #######
  postgres:
    image: 'postgres:18.4-alpine3.22@sha256:774521500f4c22761b25a6bdb772a0a3c2e8dd32468210bdad9231c5752ea398'
    restart: always
    environment:
      POSTGRES_DB: speckle
      POSTGRES_USER: speckle
      POSTGRES_PASSWORD: speckle
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql
      - ./setup/db/10-docker_postgres_init.sql:/docker-entrypoint-initdb.d/10-docker_postgres_init.sql
      - ./setup/db/11-docker_postgres_authentik_init.sql:/docker-entrypoint-initdb.d/11-docker_postgres_authentik_init.sql
    command: postgres -c max_prepared_transactions=150

  redis:
    image: "valkey/valkey:8.1-alpine@sha256:0d27f0bca0249f61d060029a6aaf2e16b2c417d68d02a508e1dfb763fa2948b4"
    restart: always
    volumes:
      - ./.volumes/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  garage:
    image: "dxflrs/garage:v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020"
    command: /garage server --single-node --default-access-key --default-bucket
    restart: always
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: "minioadmin"
      GARAGE_DEFAULT_SECRET_KEY: "minioadminminioadmin"
      GARAGE_DEFAULT_BUCKET: "speckle-server"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - ./.volumes/garage-data:/data
    ports:
      - '127.0.0.1:9000:9000'
    healthcheck:
      test: ["CMD", "/garage", "health"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 5s

  speckle-server:
    image: ghcr.io/specklesystems/speckle-server:latest
    restart: always
    healthcheck:
      test:
        - CMD
        - /nodejs/bin/node
        - -e
        - "try { require('node:http').request({headers: {'Content-Type': 'application/json'}, port:3000, hostname:'127.0.0.1', path:'/readiness', method: 'GET', timeout: 2000 }, (res) => { body = ''; res.on('data', (chunk) => {body += chunk;}); res.on('end', () => {process.exit(Number(res.statusCode != 200 || body.toLowerCase().includes('error')));}); }).end(); } catch { process.exit(1); }"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 90s
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
      garage:
        condition: service_healthy
    environment:
      CANONICAL_URL: "http://127.0.0.1:3000"
      SPECKLE_AUTOMATE_URL: "http://127.0.0.1:3030"
      FRONTEND_ORIGIN: "http://127.0.0.1:8081"
      BIND_ADDRESS: "0.0.0.0"
      # TODO: Change thvolumes:
      REDIS_URL: "redis://redis"

      S3_ENDPOINT: "http://garage:9000"
      S3_PUBLIC_ENDPOINT: "http://127.0.0.1:9000"
      S3_ACCESS_KEY: "minioadmin"
      S3_SECRET_KEY: "minioadminminioadmin"
      S3_BUCKET: "speckle-server"
      S3_CREATE_BUCKET: "true"

      FILE_SIZE_LIMIT_MB: 100
      MAX_PROJECT_MODELS_PER_PAGE: 500

      # TODO: Change this to a unique secret for this server
      SESSION_SECRET: "TODO:ReplaceWithLongString"

      STRATEGY_LOCAL: "true"

      POSTGRES_URL: 'postgres://speckle:speckle@postgres:5432/speckle'
      ENABLE_MP: "false"

      LOG_PRETTY: "true"

networks:
  default:
    name: speckle-server

volumes:
  postgres-data:
  redis-data:
  garage-data:
