# generated by datamodel-codegen:
#   filename:  Interval2d.json
#   timestamp: 2020-11-24T16:33:14+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Interval(BaseModel):
    start: Optional[Optional[float]] = None
    end: Optional[Optional[float]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Interval2d(BaseModel):
    u: Optional[Interval] = None
    v: Optional[Interval] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None
