# generated by datamodel-codegen:
#   filename:  Arc.json
#   timestamp: 2020-11-18T11:56:10+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Interval(BaseModel):
    start: Optional[Optional[float]] = None
    end: Optional[Optional[float]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Point(BaseModel):
    value: Optional[List[float]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Vector(BaseModel):
    value: Optional[List[float]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Plane(BaseModel):
    origin: Optional[Point] = None
    normal: Optional[Vector] = None
    xdir: Optional[Vector] = None
    ydir: Optional[Vector] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Arc(BaseModel):
    radius: Optional[Optional[float]] = None
    startAngle: Optional[Optional[float]] = None
    endAngle: Optional[Optional[float]] = None
    angleRadians: Optional[Optional[float]] = None
    plane: Optional[Plane] = None
    domain: Optional[Interval] = None
    startPoint: Optional[Point] = None
    midPoint: Optional[Point] = None
    endPoint: Optional[Point] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None
