# generated by datamodel-codegen:
#   filename:  Block.json
#   timestamp: 2020-11-24T16:33:01+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Base(BaseModel):
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Block(BaseModel):
    description: Optional[Optional[str]] = None
    objects: Optional[List[Base]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None
