# generated by datamodel-codegen:
#   filename:  Polycurve.json
#   timestamp: 2020-11-24T16:33:20+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class ICurve(BaseModel):
    __root__: Optional[Dict[str, Any]]


class Interval(BaseModel):
    start: Optional[Optional[float]] = None
    end: Optional[Optional[float]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None


class Polycurve(BaseModel):
    segments: Optional[List[ICurve]] = None
    domain: Optional[Interval] = None
    closed: Optional[bool] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None
