# generated by datamodel-codegen:
#   filename:  RevitUtils.json
#   timestamp: 2020-11-24T16:33:30+00:00

from __future__ import annotations

from pydantic import BaseModel


class RevitUtils(BaseModel):
    pass
