# generated by datamodel-codegen:
#   filename:  RoomBoundaryLine.json
#   timestamp: 2020-11-24T16:33:35+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel


class ICurve(BaseModel):
    __root__: Optional[Dict[str, Any]]


class RoomBoundaryLine(BaseModel):
    baseCurve: Optional[ICurve] = None
    parameters: Optional[Optional[Dict[str, Any]]] = None
    id: Optional[Optional[str]] = None
    totalChildrenCount: Optional[int] = None
    applicationId: Optional[Optional[str]] = None
    speckle_type: Optional[Optional[str]] = None
