site_name: Specklepy Docs
theme:
  name: material
  favicon: assets/speckle_logo.png
  logo: assets/speckle_logo.png
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      logo: assets/logo_white.png
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
- css/mkdocstrings.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            parameter_headings: false
            members_order: source
            separate_signature: true
            filters: ["!^_"] #Ignore _ prefixed properties
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_if_no_docstring: true
            show_labels: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_bases: false
            heading_level: 3

          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
